version: '3.8'

services:
  nudges:
    build: .
    volumes:
      - .:/usr/src/personalised_nudges
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    expose: 
      - 5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8083

volumes:
  postgres_data: